import { LakeCardProps } from '@/types/interfaces';

export const lakes: LakeCardProps[] = [
  {
    id: 1,
    lakeName: 'Озеро "Трофейне"',
    instagramLink: '',
    facebookLink: 'https://www.facebook.com/profile.php?id=100001293125330',
    youtubeLink: '',
    websiteLink: 'https://trofeyne.kiev.ua/',
    coverImg: '/img/lakes/trofeynoe.jpg',
    lakeAddress:
      'Озеро "Трофейне", с. Личанка, Київська обл., Києво-Святошинський р-н',
  },
  {
    id: 2,
    lakeName: 'Озеро "Михайлина"',
    instagramLink: 'https://www.instagram.com/mihailyna/',
    facebookLink: 'https://www.facebook.com/mihaylyna/',
    youtubeLink: '',
    websiteLink: 'https://www.mykhailyna.com.ua/',
    coverImg: '/img/lakes/myhailyna.jpg',
    lakeAddress:
      'Київська область, Києво-Святошинський район, с. Горбовичі, вул. Мельника 8а',
  },
  {
    id: 3,
    lakeName: 'Озеро "Уляники"',
    instagramLink: 'https://www.instagram.com/mihailyna/',
    facebookLink: 'https://www.facebook.com/mihaylyna/',
    youtubeLink: '',
    websiteLink: 'https://ozero-ulyaniki.com/',
    coverImg: '/img/lakes/ulyaniki.png',
    lakeAddress: 'с. Уляники, Київська область',
  },
  {
    id: 4,
    lakeName: 'Озеро "Забір\'я"',
    instagramLink: 'https://www.instagram.com/fish_park_zabirya_riba_chok/',
    facebookLink: 'https://www.facebook.com/zabiryafishpark/',
    youtubeLink: '',
    websiteLink: 'https://www.zabirya.com.ua/',
    coverImg: '/img/lakes/ulyaniki.png',
    lakeAddress: "Київська обл., с.Забір'я",
  },
  {
    id: 5,
    lakeName: 'Рибальський клуб "Солтанівка"',
    instagramLink: '',
    facebookLink: 'https://www.facebook.com/soltanovka',
    youtubeLink: '',
    websiteLink: 'https://soltanovka.com/',
    coverImg: '/img/lakes/soltanovka.jpg',
    lakeAddress: "Київська область, с. Хлепча",
  },
  {
    id: 6,
    lakeName: 'Рибальський клуб "Солтанівка"',
    instagramLink: 'https://www.instagram.com/vovkove_ozero?igsh=MWFpdGU5a2MzNTdwZg==',
    facebookLink: 'https://www.facebook.com/vovkovelake',
    youtubeLink: '',
    websiteLink: 'https://vovkoveozero.com.ua/contact-us/',
    coverImg: '/img/lakes/vovkove.jpg',
    lakeAddress: "Шосе Київ-Харків до Баришівки, далі 8 км у напрямку с.Паришків.",
  },
  {
    id: 7,
    lakeName: 'Озеро "КарТар"',
    instagramLink: 'https://www.instagram.com/ozero_kartar',
    facebookLink: 'https://www.facebook.com/OzeroKarTar/',
    youtubeLink: 'https://www.youtube.com/c/%D0%9E%D0%B7%D0%B5%D1%80%D0%BE%D0%9A%D0%B0%D1%80%D0%A2%D0%B0%D1%80',
    websiteLink: 'https://kartar.com.ua/',
    coverImg: '/img/lakes/kartar.jpg',
    lakeAddress: "c. Тарган, Володарський р-н, Київська обл.",
  },
];
